set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports control]
set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports prosessing_done]
set_property IOSTANDARD LVCMOS33 [get_ports tx_done]
set_property IOSTANDARD LVCMOS33 [get_ports tx_out]
set_property PACKAGE_PIN V17 [get_ports enable]
set_property PACKAGE_PIN V16 [get_ports control]
set_property PACKAGE_PIN U16 [get_ports tx_done]
set_property PACKAGE_PIN E19 [get_ports prosessing_done]
set_property PACKAGE_PIN A18 [get_ports tx_out]

## Configuration options, can be used for all designs
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]